# Safe Example Monitoring Configuration for Inframan Agent
# This file contains only public endpoints safe for Git repositories
# Copy this to monitors.yml and customize with your private infrastructure

global:
  default_interval_seconds: 60
  default_timeout_seconds: 30
  default_retry_attempts: 3
  include_response_body: false

# HTTP/HTTPS Monitoring - Public APIs Only
http:
  enabled: true
  defaults:
    interval_seconds: 30
    timeout_seconds: 15
    retries: 3
    user_agent: "Inframan-Monitor/1.0"
    
  targets:
    # GitHub APIs (public, safe for Git)
    - name: "github-api-status"
      url: "https://api.github.com/status"
      method: "GET"
      expected_status: [200]
      interval_seconds: 60
      
    - name: "github-zen"
      url: "https://api.github.com/zen"
      method: "GET"
      expected_status: [200]
      interval_seconds: 90
      
    # HTTPBin test service (public, safe for Git)
    - name: "httpbin-status-200"
      url: "https://httpbin.org/status/200"
      method: "GET"
      expected_status: [200]
      interval_seconds: 45
      
    - name: "httpbin-get"
      url: "https://httpbin.org/get"
      method: "GET"
      expected_status: [200]
      interval_seconds: 45
      
    # Example domain - replace with your domain
    - name: "example-website"
      url: "https://example.com"
      method: "GET"
      expected_status: [200, 301, 302]
      interval_seconds: 120

# TCP Port Monitoring - Example Infrastructure
tcp:
  enabled: true
  defaults:
    interval_seconds: 30
    timeout_seconds: 5
    retries: 3
    
  targets:
    # Example local services - replace with your infrastructure
    - name: "local-web-server"
      host: "127.0.0.1"
      port: 80
      interval_seconds: 30
      timeout_seconds: 5
      description: "Local web server"
      
    - name: "local-database"
      host: "127.0.0.1" 
      port: 5432
      interval_seconds: 30
      timeout_seconds: 5
      description: "PostgreSQL Database"
      
    # Public services (safe for Git)
    - name: "google-dns-tcp"
      host: "8.8.8.8"
      port: 53
      interval_seconds: 60
      timeout_seconds: 3
      description: "Google DNS TCP"
      
    - name: "github-https"
      host: "github.com"
      port: 443
      interval_seconds: 120
      timeout_seconds: 5
      description: "GitHub HTTPS Port"

# PING Monitoring - Example Network Tests
ping:
  enabled: true
  defaults:
    interval_seconds: 60
    timeout_seconds: 5
    packet_count: 3
    retries: 2
    
  targets:
    # Example local network - replace with your network
    - name: "ping-localhost"
      host: "127.0.0.1"
      interval_seconds: 30
      packet_count: 3
      timeout_seconds: 3
      description: "Localhost connectivity"
      
    # Public connectivity checks (safe for Git)
    - name: "ping-google-dns"
      host: "8.8.8.8"
      interval_seconds: 60
      packet_count: 3
      timeout_seconds: 5
      description: "Google DNS connectivity"
      
    - name: "ping-cloudflare-dns"
      host: "1.1.1.1"
      interval_seconds: 60
      packet_count: 3
      timeout_seconds: 5
      description: "Cloudflare DNS connectivity"

# DNS Monitoring - Public Domain Examples
dns:
  enabled: true
  defaults:
    interval_seconds: 300
    timeout_seconds: 10
    retries: 2
    dns_server: "8.8.8.8"
    
  targets:
    # Public domains (safe for Git)
    - name: "dns-github"
      domain: "github.com"
      record_type: "A"
      interval_seconds: 600
      timeout_seconds: 10
      description: "GitHub DNS resolution"
      
    - name: "dns-google"
      domain: "google.com"
      record_type: "A"
      interval_seconds: 600
      timeout_seconds: 10
      description: "Google DNS resolution"
      
    # DNS server health (safe for Git)
    - name: "dns-google-check"
      domain: "google.com"
      record_type: "A"
      dns_server: "8.8.8.8"
      interval_seconds: 300
      timeout_seconds: 5
      description: "Google DNS server health"