# US East 1 - Core API Monitoring
# Monitors: buildInfo, platform APIs, recommendations

global:
  default_interval_seconds: 90
  default_timeout_seconds: 30
  default_retry_attempts: 3
  # Performance Thresholds (in milliseconds)
  response_time_thresholds:
    warning: 500      # Yellow threshold
    critical: 1000    # Red threshold

serviceGroups:
  - name: "Core Platform APIs - us-east-1"
    description: "Essential RichRelevance platform APIs from us-east-1"
    services:
      - name: "Public IP Info "
        baseUrl: "https://ipinfo.io"
        monitors:
          - name: "us-east-1-public-ip-info"
            url: "/json"
            method: "GET"
            type: "HTTPS"
            interval: 60
            timeout: 15
            retryCount: 2
            include_response_body: true
            thresholds:
              warning: 300    # Custom warning threshold (ms)
              critical: 800   # Custom critical threshold (ms)
      - name: "Open Library"
        description: "Open Library API"
        baseUrl: "https://openlibrary.org"
        monitors:
          - name: "open-library-recent-changes"
            url: "/recentchanges.json?limit=5"
            method: "GET"
            type: "HTTPS"
            interval: 150
            timeout: 15
            retryCount: 2
            include_response_body: false
            thresholds:
              warning: 700    # Library API - moderate expectation
              critical: 1200
          - name: "open-library-search"
            url: "/search.json?q=the+lord+of+the+rings"
            method: "GET"
            type: "HTTPS"
            interval: 200
            timeout: 20
            retryCount: 2
            include_response_body: false
            thresholds:
              warning: 1000   # Search operations can be slower
              critical: 2000
          - name: "open-library-book-details"
            url: "/works/OL82563W.json"
            method: "GET"
            type: "HTTPS"
            interval: 250
            timeout: 15
            retryCount: 2
            include_response_body: true
            thresholds:
              warning: 500    # Simple lookup should be fast
              critical: 1000
      - name: "SpaceX API"
        baseUrl: "https://api.spacexdata.com"
        monitors:
          - name: "us-east-1-spacex-launches"
            url: "/v5/launches/latest"
            method: "GET"
            type: "HTTPS"
            interval: 120
            timeout: 20
            retryCount: 2
            include_response_body: true
            thresholds:
              warning: 600    # Custom warning threshold (ms)
              critical: 1200  # Custom critical threshold (ms)
monitors:
  monitors:
  - name: "us-west-2-raspberry-pi-periphery-8120"
    host: "192.168.0.104"
    port: 8120
    type: "TCP"
    interval: 180
    timeout: 10
    retryCount: 2