# US West 2 - Search & Discovery API Monitoring
# Monitors: find APIs, autocomplete, social proof, category recommendations

global:
  default_interval_seconds: 90
  default_timeout_seconds: 30
  default_retry_attempts: 3
  include_response_body: false
  # Performance Thresholds (in milliseconds)
  response_time_thresholds:
    warning: 500      # Yellow threshold
    critical: 1000    # Red threshold

serviceGroups:
  - name: "Search & Discovery APIs - us-west-2" 
    description: "Search, autocomplete and social proof APIs from us-west-2"
    services:
      - name: "API Guru"
        description: "APIs.guru - OpenAPI Directory"
        baseUrl: "https://api.apis.guru"
        monitors:
          - name: "apis-guru-openapi"
            url: "v2/apigee.net.json"
            method: "GET"
            type: "HTTPS"
            interval: 120
            timeout: 20
            retryCount: 2
            include_response_body: true
            thresholds:
              warning: 400    # Custom warning threshold (ms)
              critical: 900   # Custom critical threshold (ms)
      - name: "US Weather"
        description: "US Weather API"
        baseUrl: "https://api.weather.gov"
        monitors:
          - name: "us-weather-glossary"
            url: "/glossary"
            method: "GET"
            type: "HTTPS"
            interval: 180
            timeout: 25
            retryCount: 2
            include_response_body: true
            thresholds:
              warning: 800    # Government APIs can be slower
              critical: 1500  # But still need reasonable limits
      - name: "Open Library"
        description: "Open Library API"
        baseUrl: "https://openlibrary.org"
        monitors:
          - name: "open-library-recent-changes"
            url: "/recentchanges.json?limit=5"
            method: "GET"
            type: "HTTPS"
            interval: 150
            timeout: 15
            retryCount: 2
            include_response_body: false
            thresholds:
              warning: 700    # Library API - moderate expectation
              critical: 1200
          - name: "open-library-search"
            url: "/search.json?q=the+lord+of+the+rings"
            method: "GET"
            type: "HTTPS"
            interval: 200
            timeout: 20
            retryCount: 2
            include_response_body: false
            thresholds:
              warning: 1000   # Search operations can be slower
              critical: 2000
          - name: "open-library-book-details"
            url: "/works/OL82563W.json"
            method: "GET"
            type: "HTTPS"
            interval: 250
            timeout: 15
            retryCount: 2
            include_response_body: true
            thresholds:
              warning: 500    # Simple lookup should be fast
              critical: 1000