package vibhuvi.oio.inframirror.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AgentLockAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgentLockAllPropertiesEquals(AgentLock expected, AgentLock actual) {
        assertAgentLockAutoGeneratedPropertiesEquals(expected, actual);
        assertAgentLockAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgentLockAllUpdatablePropertiesEquals(AgentLock expected, AgentLock actual) {
        assertAgentLockUpdatableFieldsEquals(expected, actual);
        assertAgentLockUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgentLockAutoGeneratedPropertiesEquals(AgentLock expected, AgentLock actual) {
        assertThat(actual)
            .as("Verify AgentLock auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgentLockUpdatableFieldsEquals(AgentLock expected, AgentLock actual) {
        assertThat(actual)
            .as("Verify AgentLock relevant properties")
            .satisfies(a -> assertThat(a.getAgentId()).as("check agentId").isEqualTo(expected.getAgentId()))
            .satisfies(a -> assertThat(a.getAcquiredAt()).as("check acquiredAt").isEqualTo(expected.getAcquiredAt()))
            .satisfies(a -> assertThat(a.getExpiresAt()).as("check expiresAt").isEqualTo(expected.getExpiresAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgentLockUpdatableRelationshipsEquals(AgentLock expected, AgentLock actual) {
        // empty method
    }
}
