package vibhuvi.oio.inframirror.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ApiKeyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiKeyAllPropertiesEquals(ApiKey expected, ApiKey actual) {
        assertApiKeyAutoGeneratedPropertiesEquals(expected, actual);
        assertApiKeyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiKeyAllUpdatablePropertiesEquals(ApiKey expected, ApiKey actual) {
        assertApiKeyUpdatableFieldsEquals(expected, actual);
        assertApiKeyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiKeyAutoGeneratedPropertiesEquals(ApiKey expected, ApiKey actual) {
        assertThat(actual)
            .as("Verify ApiKey auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiKeyUpdatableFieldsEquals(ApiKey expected, ApiKey actual) {
        assertThat(actual)
            .as("Verify ApiKey relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getKeyHash()).as("check keyHash").isEqualTo(expected.getKeyHash()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()))
            .satisfies(a -> assertThat(a.getLastUsedDate()).as("check lastUsedDate").isEqualTo(expected.getLastUsedDate()))
            .satisfies(a -> assertThat(a.getExpiresAt()).as("check expiresAt").isEqualTo(expected.getExpiresAt()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiKeyUpdatableRelationshipsEquals(ApiKey expected, ApiKey actual) {
        // empty method
    }
}
