package vibhuvi.oio.inframirror.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BrandingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrandingAllPropertiesEquals(Branding expected, Branding actual) {
        assertBrandingAutoGeneratedPropertiesEquals(expected, actual);
        assertBrandingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrandingAllUpdatablePropertiesEquals(Branding expected, Branding actual) {
        assertBrandingUpdatableFieldsEquals(expected, actual);
        assertBrandingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrandingAutoGeneratedPropertiesEquals(Branding expected, Branding actual) {
        assertThat(actual)
            .as("Verify Branding auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrandingUpdatableFieldsEquals(Branding expected, Branding actual) {
        assertThat(actual)
            .as("Verify Branding relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getKeywords()).as("check keywords").isEqualTo(expected.getKeywords()))
            .satisfies(a -> assertThat(a.getAuthor()).as("check author").isEqualTo(expected.getAuthor()))
            .satisfies(a -> assertThat(a.getFaviconPath()).as("check faviconPath").isEqualTo(expected.getFaviconPath()))
            .satisfies(a -> assertThat(a.getLogoPath()).as("check logoPath").isEqualTo(expected.getLogoPath()))
            .satisfies(a -> assertThat(a.getLogoWidth()).as("check logoWidth").isEqualTo(expected.getLogoWidth()))
            .satisfies(a -> assertThat(a.getLogoHeight()).as("check logoHeight").isEqualTo(expected.getLogoHeight()))
            .satisfies(a -> assertThat(a.getFooterTitle()).as("check footerTitle").isEqualTo(expected.getFooterTitle()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrandingUpdatableRelationshipsEquals(Branding expected, Branding actual) {
        // empty method
    }
}
