package vibhuvi.oio.inframirror.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HttpHeartbeatAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHttpHeartbeatAllPropertiesEquals(HttpHeartbeat expected, HttpHeartbeat actual) {
        assertHttpHeartbeatAutoGeneratedPropertiesEquals(expected, actual);
        assertHttpHeartbeatAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHttpHeartbeatAllUpdatablePropertiesEquals(HttpHeartbeat expected, HttpHeartbeat actual) {
        assertHttpHeartbeatUpdatableFieldsEquals(expected, actual);
        assertHttpHeartbeatUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHttpHeartbeatAutoGeneratedPropertiesEquals(HttpHeartbeat expected, HttpHeartbeat actual) {
        assertThat(actual)
            .as("Verify HttpHeartbeat auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHttpHeartbeatUpdatableFieldsEquals(HttpHeartbeat expected, HttpHeartbeat actual) {
        assertThat(actual)
            .as("Verify HttpHeartbeat relevant properties")
            .satisfies(a -> assertThat(a.getExecutedAt()).as("check executedAt").isEqualTo(expected.getExecutedAt()))
            .satisfies(a -> assertThat(a.getSuccess()).as("check success").isEqualTo(expected.getSuccess()))
            .satisfies(a -> assertThat(a.getResponseTimeMs()).as("check responseTimeMs").isEqualTo(expected.getResponseTimeMs()))
            .satisfies(a -> assertThat(a.getResponseSizeBytes()).as("check responseSizeBytes").isEqualTo(expected.getResponseSizeBytes()))
            .satisfies(a -> assertThat(a.getResponseStatusCode()).as("check responseStatusCode").isEqualTo(expected.getResponseStatusCode())
            )
            .satisfies(a ->
                assertThat(a.getResponseContentType()).as("check responseContentType").isEqualTo(expected.getResponseContentType())
            )
            .satisfies(a -> assertThat(a.getResponseServer()).as("check responseServer").isEqualTo(expected.getResponseServer()))
            .satisfies(a ->
                assertThat(a.getResponseCacheStatus()).as("check responseCacheStatus").isEqualTo(expected.getResponseCacheStatus())
            )
            .satisfies(a -> assertThat(a.getDnsLookupMs()).as("check dnsLookupMs").isEqualTo(expected.getDnsLookupMs()))
            .satisfies(a -> assertThat(a.getDnsResolvedIp()).as("check dnsResolvedIp").isEqualTo(expected.getDnsResolvedIp()))
            .satisfies(a -> assertThat(a.getTcpConnectMs()).as("check tcpConnectMs").isEqualTo(expected.getTcpConnectMs()))
            .satisfies(a -> assertThat(a.getTlsHandshakeMs()).as("check tlsHandshakeMs").isEqualTo(expected.getTlsHandshakeMs()))
            .satisfies(a ->
                assertThat(a.getSslCertificateValid()).as("check sslCertificateValid").isEqualTo(expected.getSslCertificateValid())
            )
            .satisfies(a ->
                assertThat(a.getSslCertificateExpiry()).as("check sslCertificateExpiry").isEqualTo(expected.getSslCertificateExpiry())
            )
            .satisfies(a ->
                assertThat(a.getSslCertificateIssuer()).as("check sslCertificateIssuer").isEqualTo(expected.getSslCertificateIssuer())
            )
            .satisfies(a -> assertThat(a.getSslDaysUntilExpiry()).as("check sslDaysUntilExpiry").isEqualTo(expected.getSslDaysUntilExpiry())
            )
            .satisfies(a -> assertThat(a.getTimeToFirstByteMs()).as("check timeToFirstByteMs").isEqualTo(expected.getTimeToFirstByteMs()))
            .satisfies(a -> assertThat(a.getWarningThresholdMs()).as("check warningThresholdMs").isEqualTo(expected.getWarningThresholdMs())
            )
            .satisfies(a ->
                assertThat(a.getCriticalThresholdMs()).as("check criticalThresholdMs").isEqualTo(expected.getCriticalThresholdMs())
            )
            .satisfies(a -> assertThat(a.getErrorType()).as("check errorType").isEqualTo(expected.getErrorType()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getRawRequestHeaders()).as("check rawRequestHeaders").isEqualTo(expected.getRawRequestHeaders()))
            .satisfies(a -> assertThat(a.getRawResponseHeaders()).as("check rawResponseHeaders").isEqualTo(expected.getRawResponseHeaders())
            )
            .satisfies(a -> assertThat(a.getRawResponseBody()).as("check rawResponseBody").isEqualTo(expected.getRawResponseBody()))
            .satisfies(a -> assertThat(a.getDnsDetails()).as("check dnsDetails").isEqualTo(expected.getDnsDetails()))
            .satisfies(a -> assertThat(a.getTlsDetails()).as("check tlsDetails").isEqualTo(expected.getTlsDetails()))
            .satisfies(a -> assertThat(a.getHttpVersion()).as("check httpVersion").isEqualTo(expected.getHttpVersion()))
            .satisfies(a -> assertThat(a.getContentEncoding()).as("check contentEncoding").isEqualTo(expected.getContentEncoding()))
            .satisfies(a -> assertThat(a.getCompressionRatio()).as("check compressionRatio").isEqualTo(expected.getCompressionRatio()))
            .satisfies(a -> assertThat(a.getTransferEncoding()).as("check transferEncoding").isEqualTo(expected.getTransferEncoding()))
            .satisfies(a -> assertThat(a.getResponseBodyHash()).as("check responseBodyHash").isEqualTo(expected.getResponseBodyHash()))
            .satisfies(a -> assertThat(a.getResponseBodySample()).as("check responseBodySample").isEqualTo(expected.getResponseBodySample())
            )
            .satisfies(a -> assertThat(a.getResponseBodyValid()).as("check responseBodyValid").isEqualTo(expected.getResponseBodyValid()))
            .satisfies(a ->
                assertThat(a.getResponseBodyUncompressedBytes())
                    .as("check responseBodyUncompressedBytes")
                    .isEqualTo(expected.getResponseBodyUncompressedBytes())
            )
            .satisfies(a -> assertThat(a.getRedirectDetails()).as("check redirectDetails").isEqualTo(expected.getRedirectDetails()))
            .satisfies(a -> assertThat(a.getCacheControl()).as("check cacheControl").isEqualTo(expected.getCacheControl()))
            .satisfies(a -> assertThat(a.getEtag()).as("check etag").isEqualTo(expected.getEtag()))
            .satisfies(a -> assertThat(a.getCacheAge()).as("check cacheAge").isEqualTo(expected.getCacheAge()))
            .satisfies(a -> assertThat(a.getCdnProvider()).as("check cdnProvider").isEqualTo(expected.getCdnProvider()))
            .satisfies(a -> assertThat(a.getCdnPop()).as("check cdnPop").isEqualTo(expected.getCdnPop()))
            .satisfies(a -> assertThat(a.getRateLimitDetails()).as("check rateLimitDetails").isEqualTo(expected.getRateLimitDetails()))
            .satisfies(a -> assertThat(a.getNetworkPath()).as("check networkPath").isEqualTo(expected.getNetworkPath()))
            .satisfies(a -> assertThat(a.getAgentMetrics()).as("check agentMetrics").isEqualTo(expected.getAgentMetrics()))
            .satisfies(a -> assertThat(a.getPhaseLatencies()).as("check phaseLatencies").isEqualTo(expected.getPhaseLatencies()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHttpHeartbeatUpdatableRelationshipsEquals(HttpHeartbeat expected, HttpHeartbeat actual) {
        assertThat(actual)
            .as("Verify HttpHeartbeat relationships")
            .satisfies(a -> assertThat(a.getAgent()).as("check agent").isEqualTo(expected.getAgent()))
            .satisfies(a -> assertThat(a.getMonitor()).as("check monitor").isEqualTo(expected.getMonitor()));
    }
}
