package vibhuvi.oio.inframirror.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InstanceHeartbeatAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstanceHeartbeatAllPropertiesEquals(InstanceHeartbeat expected, InstanceHeartbeat actual) {
        assertInstanceHeartbeatAutoGeneratedPropertiesEquals(expected, actual);
        assertInstanceHeartbeatAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstanceHeartbeatAllUpdatablePropertiesEquals(InstanceHeartbeat expected, InstanceHeartbeat actual) {
        assertInstanceHeartbeatUpdatableFieldsEquals(expected, actual);
        assertInstanceHeartbeatUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstanceHeartbeatAutoGeneratedPropertiesEquals(InstanceHeartbeat expected, InstanceHeartbeat actual) {
        assertThat(actual)
            .as("Verify InstanceHeartbeat auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstanceHeartbeatUpdatableFieldsEquals(InstanceHeartbeat expected, InstanceHeartbeat actual) {
        assertThat(actual)
            .as("Verify InstanceHeartbeat relevant properties")
            .satisfies(a -> assertThat(a.getExecutedAt()).as("check executedAt").isEqualTo(expected.getExecutedAt()))
            .satisfies(a -> assertThat(a.getHeartbeatType()).as("check heartbeatType").isEqualTo(expected.getHeartbeatType()))
            .satisfies(a -> assertThat(a.getSuccess()).as("check success").isEqualTo(expected.getSuccess()))
            .satisfies(a -> assertThat(a.getResponseTimeMs()).as("check responseTimeMs").isEqualTo(expected.getResponseTimeMs()))
            .satisfies(a -> assertThat(a.getPacketLoss()).as("check packetLoss").isEqualTo(expected.getPacketLoss()))
            .satisfies(a -> assertThat(a.getJitterMs()).as("check jitterMs").isEqualTo(expected.getJitterMs()))
            .satisfies(a -> assertThat(a.getCpuUsage()).as("check cpuUsage").isEqualTo(expected.getCpuUsage()))
            .satisfies(a -> assertThat(a.getMemoryUsage()).as("check memoryUsage").isEqualTo(expected.getMemoryUsage()))
            .satisfies(a -> assertThat(a.getDiskUsage()).as("check diskUsage").isEqualTo(expected.getDiskUsage()))
            .satisfies(a -> assertThat(a.getLoadAverage()).as("check loadAverage").isEqualTo(expected.getLoadAverage()))
            .satisfies(a -> assertThat(a.getProcessCount()).as("check processCount").isEqualTo(expected.getProcessCount()))
            .satisfies(a -> assertThat(a.getNetworkRxBytes()).as("check networkRxBytes").isEqualTo(expected.getNetworkRxBytes()))
            .satisfies(a -> assertThat(a.getNetworkTxBytes()).as("check networkTxBytes").isEqualTo(expected.getNetworkTxBytes()))
            .satisfies(a -> assertThat(a.getUptimeSeconds()).as("check uptimeSeconds").isEqualTo(expected.getUptimeSeconds()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getErrorType()).as("check errorType").isEqualTo(expected.getErrorType()))
            .satisfies(a -> assertThat(a.getMetadata()).as("check metadata").isEqualTo(expected.getMetadata()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstanceHeartbeatUpdatableRelationshipsEquals(InstanceHeartbeat expected, InstanceHeartbeat actual) {
        assertThat(actual)
            .as("Verify InstanceHeartbeat relationships")
            .satisfies(a -> assertThat(a.getAgent()).as("check agent").isEqualTo(expected.getAgent()))
            .satisfies(a -> assertThat(a.getInstance()).as("check instance").isEqualTo(expected.getInstance()));
    }
}
