package vibhuvi.oio.inframirror.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InstanceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstanceAllPropertiesEquals(Instance expected, Instance actual) {
        assertInstanceAutoGeneratedPropertiesEquals(expected, actual);
        assertInstanceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstanceAllUpdatablePropertiesEquals(Instance expected, Instance actual) {
        assertInstanceUpdatableFieldsEquals(expected, actual);
        assertInstanceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstanceAutoGeneratedPropertiesEquals(Instance expected, Instance actual) {
        assertThat(actual)
            .as("Verify Instance auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstanceUpdatableFieldsEquals(Instance expected, Instance actual) {
        assertThat(actual)
            .as("Verify Instance relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getHostname()).as("check hostname").isEqualTo(expected.getHostname()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getInstanceType()).as("check instanceType").isEqualTo(expected.getInstanceType()))
            .satisfies(a -> assertThat(a.getOperatingSystem()).as("check operatingSystem").isEqualTo(expected.getOperatingSystem()))
            .satisfies(a -> assertThat(a.getPlatform()).as("check platform").isEqualTo(expected.getPlatform()))
            .satisfies(a -> assertThat(a.getPrivateIpAddress()).as("check privateIpAddress").isEqualTo(expected.getPrivateIpAddress()))
            .satisfies(a -> assertThat(a.getPublicIpAddress()).as("check publicIpAddress").isEqualTo(expected.getPublicIpAddress()))
            .satisfies(a -> assertThat(a.getTags()).as("check tags").isEqualTo(expected.getTags()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstanceUpdatableRelationshipsEquals(Instance expected, Instance actual) {
        assertThat(actual)
            .as("Verify Instance relationships")
            .satisfies(a -> assertThat(a.getDatacenter()).as("check datacenter").isEqualTo(expected.getDatacenter()))
            .satisfies(a -> assertThat(a.getAgent()).as("check agent").isEqualTo(expected.getAgent()));
    }
}
