package vibhuvi.oio.inframirror.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ServiceHeartbeatAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceHeartbeatAllPropertiesEquals(ServiceHeartbeat expected, ServiceHeartbeat actual) {
        assertServiceHeartbeatAutoGeneratedPropertiesEquals(expected, actual);
        assertServiceHeartbeatAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceHeartbeatAllUpdatablePropertiesEquals(ServiceHeartbeat expected, ServiceHeartbeat actual) {
        assertServiceHeartbeatUpdatableFieldsEquals(expected, actual);
        assertServiceHeartbeatUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceHeartbeatAutoGeneratedPropertiesEquals(ServiceHeartbeat expected, ServiceHeartbeat actual) {
        assertThat(actual)
            .as("Verify ServiceHeartbeat auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceHeartbeatUpdatableFieldsEquals(ServiceHeartbeat expected, ServiceHeartbeat actual) {
        assertThat(actual)
            .as("Verify ServiceHeartbeat relevant properties")
            .satisfies(a -> assertThat(a.getExecutedAt()).as("check executedAt").isEqualTo(expected.getExecutedAt()))
            .satisfies(a -> assertThat(a.getSuccess()).as("check success").isEqualTo(expected.getSuccess()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getResponseTimeMs()).as("check responseTimeMs").isEqualTo(expected.getResponseTimeMs()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getMetadata()).as("check metadata").isEqualTo(expected.getMetadata()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceHeartbeatUpdatableRelationshipsEquals(ServiceHeartbeat expected, ServiceHeartbeat actual) {
        assertThat(actual)
            .as("Verify ServiceHeartbeat relationships")
            .satisfies(a -> assertThat(a.getAgent()).as("check agent").isEqualTo(expected.getAgent()))
            .satisfies(a -> assertThat(a.getMonitoredService()).as("check monitoredService").isEqualTo(expected.getMonitoredService()))
            .satisfies(a -> assertThat(a.getServiceInstance()).as("check serviceInstance").isEqualTo(expected.getServiceInstance()));
    }
}
