package vibhuvi.oio.inframirror.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ServiceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceAllPropertiesEquals(Service expected, Service actual) {
        assertServiceAutoGeneratedPropertiesEquals(expected, actual);
        assertServiceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceAllUpdatablePropertiesEquals(Service expected, Service actual) {
        assertServiceUpdatableFieldsEquals(expected, actual);
        assertServiceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceAutoGeneratedPropertiesEquals(Service expected, Service actual) {
        assertThat(actual)
            .as("Verify Service auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceUpdatableFieldsEquals(Service expected, Service actual) {
        assertThat(actual)
            .as("Verify Service relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getServiceType()).as("check serviceType").isEqualTo(expected.getServiceType()))
            .satisfies(a -> assertThat(a.getEnvironment()).as("check environment").isEqualTo(expected.getEnvironment()))
            .satisfies(a -> assertThat(a.getMonitoringEnabled()).as("check monitoringEnabled").isEqualTo(expected.getMonitoringEnabled()))
            .satisfies(a ->
                assertThat(a.getClusterMonitoringEnabled())
                    .as("check clusterMonitoringEnabled")
                    .isEqualTo(expected.getClusterMonitoringEnabled())
            )
            .satisfies(a -> assertThat(a.getIntervalSeconds()).as("check intervalSeconds").isEqualTo(expected.getIntervalSeconds()))
            .satisfies(a -> assertThat(a.getTimeoutMs()).as("check timeoutMs").isEqualTo(expected.getTimeoutMs()))
            .satisfies(a -> assertThat(a.getRetryCount()).as("check retryCount").isEqualTo(expected.getRetryCount()))
            .satisfies(a -> assertThat(a.getLatencyWarningMs()).as("check latencyWarningMs").isEqualTo(expected.getLatencyWarningMs()))
            .satisfies(a -> assertThat(a.getLatencyCriticalMs()).as("check latencyCriticalMs").isEqualTo(expected.getLatencyCriticalMs()))
            .satisfies(a -> assertThat(a.getAdvancedConfig()).as("check advancedConfig").isEqualTo(expected.getAdvancedConfig()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceUpdatableRelationshipsEquals(Service expected, Service actual) {
        assertThat(actual)
            .as("Verify Service relationships")
            .satisfies(a -> assertThat(a.getDatacenter()).as("check datacenter").isEqualTo(expected.getDatacenter()));
    }
}
