package vibhuvi.oio.inframirror.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ServiceInstanceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceInstanceAllPropertiesEquals(ServiceInstance expected, ServiceInstance actual) {
        assertServiceInstanceAutoGeneratedPropertiesEquals(expected, actual);
        assertServiceInstanceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceInstanceAllUpdatablePropertiesEquals(ServiceInstance expected, ServiceInstance actual) {
        assertServiceInstanceUpdatableFieldsEquals(expected, actual);
        assertServiceInstanceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceInstanceAutoGeneratedPropertiesEquals(ServiceInstance expected, ServiceInstance actual) {
        assertThat(actual)
            .as("Verify ServiceInstance auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceInstanceUpdatableFieldsEquals(ServiceInstance expected, ServiceInstance actual) {
        assertThat(actual)
            .as("Verify ServiceInstance relevant properties")
            .satisfies(a -> assertThat(a.getPort()).as("check port").isEqualTo(expected.getPort()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceInstanceUpdatableRelationshipsEquals(ServiceInstance expected, ServiceInstance actual) {
        assertThat(actual)
            .as("Verify ServiceInstance relationships")
            .satisfies(a -> assertThat(a.getInstance()).as("check instance").isEqualTo(expected.getInstance()))
            .satisfies(a -> assertThat(a.getMonitoredService()).as("check monitoredService").isEqualTo(expected.getMonitoredService()));
    }
}
