package vibhuvi.oio.inframirror.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SessionLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionLogAllPropertiesEquals(SessionLog expected, SessionLog actual) {
        assertSessionLogAutoGeneratedPropertiesEquals(expected, actual);
        assertSessionLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionLogAllUpdatablePropertiesEquals(SessionLog expected, SessionLog actual) {
        assertSessionLogUpdatableFieldsEquals(expected, actual);
        assertSessionLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionLogAutoGeneratedPropertiesEquals(SessionLog expected, SessionLog actual) {
        assertThat(actual)
            .as("Verify SessionLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionLogUpdatableFieldsEquals(SessionLog expected, SessionLog actual) {
        assertThat(actual)
            .as("Verify SessionLog relevant properties")
            .satisfies(a -> assertThat(a.getSessionType()).as("check sessionType").isEqualTo(expected.getSessionType()))
            .satisfies(a -> assertThat(a.getStartTime()).as("check startTime").isEqualTo(expected.getStartTime()))
            .satisfies(a -> assertThat(a.getEndTime()).as("check endTime").isEqualTo(expected.getEndTime()))
            .satisfies(a -> assertThat(a.getDuration()).as("check duration").isEqualTo(expected.getDuration()))
            .satisfies(a -> assertThat(a.getSourceIpAddress()).as("check sourceIpAddress").isEqualTo(expected.getSourceIpAddress()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getTerminationReason()).as("check terminationReason").isEqualTo(expected.getTerminationReason()))
            .satisfies(a -> assertThat(a.getCommandsExecuted()).as("check commandsExecuted").isEqualTo(expected.getCommandsExecuted()))
            .satisfies(a -> assertThat(a.getBytesTransferred()).as("check bytesTransferred").isEqualTo(expected.getBytesTransferred()))
            .satisfies(a -> assertThat(a.getSessionId()).as("check sessionId").isEqualTo(expected.getSessionId()))
            .satisfies(a -> assertThat(a.getMetadata()).as("check metadata").isEqualTo(expected.getMetadata()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSessionLogUpdatableRelationshipsEquals(SessionLog expected, SessionLog actual) {
        assertThat(actual)
            .as("Verify SessionLog relationships")
            .satisfies(a -> assertThat(a.getInstance()).as("check instance").isEqualTo(expected.getInstance()))
            .satisfies(a -> assertThat(a.getAgent()).as("check agent").isEqualTo(expected.getAgent()));
    }
}
