package vibhuvi.oio.inframirror.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StatusPageItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusPageItemAllPropertiesEquals(StatusPageItem expected, StatusPageItem actual) {
        assertStatusPageItemAutoGeneratedPropertiesEquals(expected, actual);
        assertStatusPageItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusPageItemAllUpdatablePropertiesEquals(StatusPageItem expected, StatusPageItem actual) {
        assertStatusPageItemUpdatableFieldsEquals(expected, actual);
        assertStatusPageItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusPageItemAutoGeneratedPropertiesEquals(StatusPageItem expected, StatusPageItem actual) {
        assertThat(actual)
            .as("Verify StatusPageItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusPageItemUpdatableFieldsEquals(StatusPageItem expected, StatusPageItem actual) {
        assertThat(actual)
            .as("Verify StatusPageItem relevant properties")
            .satisfies(a -> assertThat(a.getItemType()).as("check itemType").isEqualTo(expected.getItemType()))
            .satisfies(a -> assertThat(a.getItemId()).as("check itemId").isEqualTo(expected.getItemId()))
            .satisfies(a -> assertThat(a.getDisplayOrder()).as("check displayOrder").isEqualTo(expected.getDisplayOrder()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusPageItemUpdatableRelationshipsEquals(StatusPageItem expected, StatusPageItem actual) {
        assertThat(actual)
            .as("Verify StatusPageItem relationships")
            .satisfies(a -> assertThat(a.getStatusPage()).as("check statusPage").isEqualTo(expected.getStatusPage()));
    }
}
