package vibhuvi.oio.inframirror.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StatusPageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusPageAllPropertiesEquals(StatusPage expected, StatusPage actual) {
        assertStatusPageAutoGeneratedPropertiesEquals(expected, actual);
        assertStatusPageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusPageAllUpdatablePropertiesEquals(StatusPage expected, StatusPage actual) {
        assertStatusPageUpdatableFieldsEquals(expected, actual);
        assertStatusPageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusPageAutoGeneratedPropertiesEquals(StatusPage expected, StatusPage actual) {
        assertThat(actual)
            .as("Verify StatusPage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusPageUpdatableFieldsEquals(StatusPage expected, StatusPage actual) {
        assertThat(actual)
            .as("Verify StatusPage relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getSlug()).as("check slug").isEqualTo(expected.getSlug()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getIsPublic()).as("check isPublic").isEqualTo(expected.getIsPublic()))
            .satisfies(a -> assertThat(a.getCustomDomain()).as("check customDomain").isEqualTo(expected.getCustomDomain()))
            .satisfies(a -> assertThat(a.getLogoUrl()).as("check logoUrl").isEqualTo(expected.getLogoUrl()))
            .satisfies(a -> assertThat(a.getThemeColor()).as("check themeColor").isEqualTo(expected.getThemeColor()))
            .satisfies(a -> assertThat(a.getHeaderText()).as("check headerText").isEqualTo(expected.getHeaderText()))
            .satisfies(a -> assertThat(a.getFooterText()).as("check footerText").isEqualTo(expected.getFooterText()))
            .satisfies(a -> assertThat(a.getShowResponseTimes()).as("check showResponseTimes").isEqualTo(expected.getShowResponseTimes()))
            .satisfies(a ->
                assertThat(a.getShowUptimePercentage()).as("check showUptimePercentage").isEqualTo(expected.getShowUptimePercentage())
            )
            .satisfies(a -> assertThat(a.getAutoRefreshSeconds()).as("check autoRefreshSeconds").isEqualTo(expected.getAutoRefreshSeconds())
            )
            .satisfies(a -> assertThat(a.getMonitorSelection()).as("check monitorSelection").isEqualTo(expected.getMonitorSelection()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getIsHomePage()).as("check isHomePage").isEqualTo(expected.getIsHomePage()))
            .satisfies(a -> assertThat(a.getAllowedRoles()).as("check allowedRoles").isEqualTo(expected.getAllowedRoles()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusPageUpdatableRelationshipsEquals(StatusPage expected, StatusPage actual) {
        // empty method
    }
}
