package vibhuvi.oio.inframirror.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StatusDependencyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusDependencyAllPropertiesEquals(StatusDependency expected, StatusDependency actual) {
        assertStatusDependencyAutoGeneratedPropertiesEquals(expected, actual);
        assertStatusDependencyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusDependencyAllUpdatablePropertiesEquals(StatusDependency expected, StatusDependency actual) {
        assertStatusDependencyUpdatableFieldsEquals(expected, actual);
        assertStatusDependencyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusDependencyAutoGeneratedPropertiesEquals(StatusDependency expected, StatusDependency actual) {
        assertThat(actual)
            .as("Verify StatusDependency auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusDependencyUpdatableFieldsEquals(StatusDependency expected, StatusDependency actual) {
        assertThat(actual)
            .as("Verify StatusDependency relevant properties")
            .satisfies(a -> assertThat(a.getParentType()).as("check parentType").isEqualTo(expected.getParentType()))
            .satisfies(a -> assertThat(a.getParentId()).as("check parentId").isEqualTo(expected.getParentId()))
            .satisfies(a -> assertThat(a.getChildType()).as("check childType").isEqualTo(expected.getChildType()))
            .satisfies(a -> assertThat(a.getChildId()).as("check childId").isEqualTo(expected.getChildId()))
            .satisfies(a -> assertThat(a.getMetadata()).as("check metadata").isEqualTo(expected.getMetadata()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusDependencyUpdatableRelationshipsEquals(StatusDependency expected, StatusDependency actual) {
        assertThat(actual)
            .as("Verify StatusDependency relationships")
            .satisfies(a -> assertThat(a.getStatusPage()).as("check statusPage").isEqualTo(expected.getStatusPage()));
    }
}
