services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: inframirror
      POSTGRES_PASSWORD: inframirror
      POSTGRES_DB: inframirror
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data

  inframirror:
    image: inframirror
    container_name: inframirror
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://inframirror:inframirror@postgres:5432/inframirror
    ports:
      - "8080:8080"