# Infragent - Infrastructure Monitoring Agent
# Agent only - connects to external PostgreSQL
services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: inframirror
      POSTGRES_PASSWORD: inframirror
      POSTGRES_DB: inframirror
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
  agent-us-east-1:
    image: infragent:latest
    container_name: infragent-us-east-1
    hostname: us-east-1-agent-01
    environment:
      # Agent Identity
      - AGENT_NAME=api-monitor-us-east-1
      - DATACENTER=us-east-1
      - AGENT_HOST=us-east-1-agent-01
      
      # Database Connection
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=inframirror
      - DATABASE_USER=inframirror
      - DATABASE_PASSWORD=inframirror
      
      # Configuration
      - MONITORS_CONFIG=/app/configs/monitors-us-east-1.yml
      - LOG_LEVEL=info
      
    volumes:
      - ./config/monitors-us-east-1.yml:/app/configs/monitors-us-east-1.yml:ro
      - ./config/agent-us-east-1.yml:/app/configs/agent.yml:ro
      - agent1_logs:/app/logs
    
    ports:
      - "8081:8081"  # Health endpoints
    restart: unless-stopped

  # Agent 2 - US West 2 (Search & Discovery APIs)
  agent-us-west-2:
    image: infragent:latest
    container_name: infragent-us-west-2
    hostname: us-west-2-agent-01
    environment:
      # Agent Identity
      - AGENT_NAME=api-monitor-us-west-2
      - DATACENTER=us-west-2
      - AGENT_HOST=us-west-2-agent-01
      
      # Database Connection
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=inframirror
      - DATABASE_USER=inframirror
      - DATABASE_PASSWORD=inframirror
      
      # Configuration
      - MONITORS_CONFIG=/app/configs/monitors-us-west-2.yml
      - LOG_LEVEL=info
      
    volumes:
      - ./config/monitors-us-west-2.yml:/app/configs/monitors-us-west-2.yml:ro
      - ./config/agent-us-west-2.yml:/app/configs/agent.yml:ro
      - agent2_logs:/app/logs
    
    ports:
      - "8082:8081"  # Health endpoints (mapped to avoid conflict)
      
    restart: unless-stopped

volumes:
  agent1_logs:
  agent2_logs:
